app.config(function ($translateProvider) {
  $translateProvider.translations('en', {
      Profile:'Your Profile',
      Title: 'Title',
      SelectTitle: '-- select your title --',
      Mrs: 'Mrs.',
      Ms: 'Miss',
      Mr:'Mr.',
      Username: 'User Name',
      Firstname: 'First Name',  
      Middlename: 'Middle Name'  ,
      Lastname: 'Last Name',
      Gender: 'Gender',
      Male: 'Male',
      Female: 'Female',
      Address1: 'Address1',
      Address2: 'Address2',
      SelectCity: '--select your city--',
      Bangkok: 'Bangkok',
      City: 'City',
      ChiangMai: 'Chiang Mai',
      Krabi: 'Krabi',
      Phuket: 'Phuket',
      Ubon: 'Ubon Ratchathani',
      Zipcode: 'Zipcode',
      Mobile: 'Mobile',
      Email: 'Email',
      Birthday: 'Birthday',
      Picture: 'Picture',
      Cancal: 'Cancal',
      Submit: 'Submit',
    FOO: 'This is a paragraph.',
    BUTTON_LANG_EN: 'english',
    BUTTON_LANG_TH: 'thai'
  });
   
  $translateProvider.translations('th', {
      Profile: 'ข้อมูลส่วนตัว',
      Title: 'คำนำหน้า',
      SelectTitle: '-- เลือกคำนำหน้า --',
      Mrs: 'นาง',
      Ms: 'น.ส.',
      Mr: 'นาย',
      Username: 'ชื่อผู้ใช้',
      Firstname: 'ชื่อ',
      Middlename: 'ชื่อกลาง',
      Lastname: 'นามสกุล',
      Gender: 'เพศ',
      Male: 'ชาย',
      Female: 'หญิง',
      Address1: 'ที่อยู่ 1',
      Address2: 'ที่อยู่ 2',
      SelectCity: '---เลือกจังหวัด---',
      Bangkok: 'กรุงเทพฯ',
      City: 'จังหวัด',
      ChiangMai: 'เชียงใหม่',
      Krabi: 'กระบี่',
      Phuket: 'ภูเก็ต',
      Ubon: 'อุบลราชธานี',
      Zipcode: 'รหัสไปรษณีย์',
      Mobile: 'เบอร์โทรศัพท์',
      Email: 'อีเมล์',
      Birthday: 'วันเกิด',
      Picture: 'ภาพโปรไฟล์',
      Cancal: 'ยกเลิก',
      Submit: 'บันทึก',
      FOO: 'Dies ist ein Paragraph.',
      BUTTON_LANG_EN: 'english',
      BUTTON_LANG_TH: 'thai'
    });
  $translateProvider.preferredLanguage('en');
});